---
title: "Untitled"
output: html_document
---

New Rscript for the chapter 1 satellite track (till May 2023)


```{r}

library(ggplot2)
library(lubridate)
library(argosfilter)
library(tidyr)
library(plyr)
library(dplyr)
library(tidyverse)
library(rnaturalearth)
library(plotly)
library(aniMotum)


```


```{r 2009}
# read the 2009 data 
# 2697 lcs
Auck_Is_SRW_2009 <- read_csv("D:/auckland/nzsrw/maps/maps/tutorial/argos/Auck_Is_SRW_2009.csv")
tags_df <- read.csv("D:/auckland/nzsrw/maps/maps/tutorial/deployment_dets/deployment_Information.csv")

Auck_Is_SRW_2009 <- Auck_Is_SRW_2009[c("Ptt", "Date", "Quality", "Longitude", "Latitude")]
names(Auck_Is_SRW_2009) <- c("id", "date", "lc", "lon", "lat")

# format the date 
Auck_Is_SRW_2009$date <- ymd_hms(Auck_Is_SRW_2009$date, tz = "GMT")

# order 
Auck_Is_SRW_2009 <- Auck_Is_SRW_2009[order(Auck_Is_SRW_2009$id, Auck_Is_SRW_2009$date),]

# Remove data generated before tag deployment (testing for example)
tags_df$deploy_dte <- ymd_hms(tags_df$Date..UTC., tz = "GMT")
tags_df$id <- tags_df$Argos.Number
Auck_Is_SRW_2009 <- ddply(tags_df, ~ id, function(d){
  dates <- d[c("deploy_dte")]
  r <- Auck_Is_SRW_2009[Auck_Is_SRW_2009$date >= dates[1,1] & 
                    Auck_Is_SRW_2009$id == d$id[1],]
  return(r)
})

# 6 whales 
length(unique(Auck_Is_SRW_2009$id))
table(Auck_Is_SRW_2009$id)
table(Auck_Is_SRW_2009$lc)

remove(tags_df)

# remove 96377 (n=3) 

Auck_Is_SRW_2009 <- Auck_Is_SRW_2009 %>% filter(id !="96377")

# Now apply the sda filter
Auck_Is_SRW_2009 <- ddply(Auck_Is_SRW_2009, ~id, function(d){
    d$argosfilter <- sdafilter(lat = d$lat, 
                               lon = d$lon, 
                               lc = d$lc, 
                               dtime = d$date, vmax = 25)
    return(d)
})

#Subset to exclude the erroneous locations

filtered_argos_df <- Auck_Is_SRW_2009 %>% 
  filter(argosfilter != "removed") %>% 
  dplyr::select(-argosfilter)

#Who is left? How many positions?
filtered_argos_df %>% 
  group_by(id) %>% 
  dplyr::summarize(nb_locations = n())

# 2415 lcs left 

#How does that compare to the raw dataset?
tab_1 <- Auck_Is_SRW_2009 %>% 
  group_by(id) %>% 
  dplyr::summarize(nb_locations = n())

tab_2 <- filtered_argos_df %>% 
  group_by(id) %>% 
  dplyr::summarize(nb_locations = n())

tab  <- plyr::join(data.frame(tab_1), data.frame(tab_2), by="id")
colnames(tab) <- c("id", "raw_locs", "filt_locs")
tab

pre_dup <- nrow(filtered_argos_df) # to get the current number of data points

# create dummy variable
filtered_argos_df$index <- c(1:nrow(filtered_argos_df))

# run each tag in a loop check to check for duplicates
# if there is a time duplicate, select the best quality position or simply the first position
filtered_argos_df <- ddply(filtered_argos_df, ~id, function(d){
  toremove <- c()
  for (i in c(2:nrow(d))) {
    if (d$date[i] == d$date[i-1]) {
      dd <- d[(i-1):i,]
      r <- dd[dd$lc == ave(dd$lc, FUN = min), "index"] # find the lowest quality
      toremove <- c(toremove, r[1]) #select first element of r in case both locations have the same lq
    }
  }
  if (length(toremove) > 0){d <- d[!(d$index %in% toremove), ]}
  return(d)
})
# remove dummy variable n=70
filtered_argos_df$index <- NULL
pre_dup - nrow(filtered_argos_df) # to get an understanding of how many duplicates were removed

# Look at the time difference between locations
time_diff_hours_df <- ddply(filtered_argos_df, ~id, function(d){
  d$time_diff_hours <- NA
  for (i in 2:nrow(d)){
    d$time_diff_hours[i] = as.numeric(difftime(d$date[i], d$date[i-1], units = "hours"))}
  return(d)
})

# mean time difference between locations (in hours)
mts <- aggregate(time_diff_hours~id, time_diff_hours_df, mean)
mts #this is the mean time step

trackseg_argos_df <- ddply(time_diff_hours_df, ~id, function(d){
ind <- which(d$time_diff_hours > 24)
d$mark <- 0
d$mark[ind] <- 1
d$track_seg <- cumsum(d$mark)
  return(d)
})

# Now create a new id based on track segment
trackseg_argos_df$track_id <- paste(trackseg_argos_df$id, "_", trackseg_argos_df$track_seg, sep="")

# check track segment 

table(trackseg_argos_df$track_id)

min_obs <- 10 ## set the number of minimum obs acceptable
trackseg_argos_df <- trackseg_argos_df %>% group_by(track_id)
trackseg_argos_df_filt <- filter(trackseg_argos_df, n() >= min_obs)
table(trackseg_argos_df_filt$track_id) #2305 locs


# Clean up the file first
ssm_df <- trackseg_argos_df_filt[,c(2:5,9)]

ssm_tdiff_hours_df <- ddply(ssm_df, ~track_id, function(d){
  d$time_diff_hours <- NA
  for (i in 2:nrow(d)){
    d$time_diff_hours[i] = as.numeric(difftime(d$date[i], d$date[i-1], units = "hours"))}
  return(d)
})

# mean time difference between locations (in hours)
mts <- aggregate(time_diff_hours~ track_id, ssm_tdiff_hours_df, mean)
mts #this is the mean time step

mean(mts$time_diff_hours)


```

```{r apply ssm model 2009}
# apply ssm model 

ssm_df <- ssm_df[,c(5,1:4)] #structure the data frame so it matches the required structure
colnames(ssm_df)[1] <- "id"
ssm_df <- data.frame(ssm_df)
save(ssm_df,file="D:/auckland/nzsrw/chapter1 07102023/2009/pre_ssm.Rdata")

# this is the ssm at the 24h time step
fit_ssm_24h <- fit_ssm(ssm_df, vmax=25, model="crw", time.step=24, control = ssm_control(verbose=0)) 

mpm_24h <-fit_mpm(fit_ssm_24h,model="mpm",control = mpm_control(verbose=0))
mpm_18h <-fit_mpm(fit_ssm_18h,model="mpm",control = mpm_control(verbose=0))
mpm_12h <-fit_mpm(fit_ssm_12h,model="mpm",control = mpm_control(verbose=0))

table(ssm_df$id)
plot(fit_ssm_12h,what="p",type=2,ask=F,alpha=0.1)
plot(mpm_12h,ask=F)


ssm_2009_df <-grab(fit_ssm_12h,what="p")
mpm_2009_df <- grab(mpm_12h,what="f")

mpm_ssm_12h<-join(fit_ssm_12h%>%filter(!id%in%c("96376_4")),mpm_12h,what.ssm="p",as_sf=F)

mpm_ssm_12h <-as.data.frame(mpm_ssm_12h)

save(mpm_ssm_12h,file="D:/auckland/nzsrw/chapter1 07102023/2009/mpm_ssm_12h_2009.Rdata")

```

```{r}
# new raw data including 2020, 2021, 2022 has 57902 locs 
raw_argos_df <- list.files(path="D:/auckland/nzsrw/maps/maps/raw_argos_07102023",pattern=".csv",full.names = TRUE)
raw_argos_df<-lapply(raw_argos_df,read.csv)
raw_argos_df<-do.call("rbind",raw_argos_df)


```